run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: true
  skip-files:
  - ".*_mock\\.go$"
  - ".*_gen\\.go$"
  - ".*\\.pb\\.([a-zA-Z0-9]+\\.)?go$"
  skip-dirs-use-default: true
  allow-parallel-runners: true

linters:
  disable-all: true
  fast: true
  enable:
  - errcheck
  - gofmt
  - gofumpt
  - gosec
  - gosimple
  - govet
  - misspell
  - ineffassign
  - revive
  - staticcheck
  - typecheck
  - unused
